services:
  web:
    container_name: web
    build: path=./webserver/
    volumes:
      - './web:/usr/share/nginx/html'
      - './node_modules:/usr/share/nginx/html/node_modules'
    restart: always
    ports:
     - '8081:8081'
